package com.ch.dao;

import com.ch.entity.BtSysUserRole;
import com.ch.entity.BtSysUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

@Repository
public interface BtSysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user_role
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    long countByExample(BtSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user_role
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int deleteByExample(BtSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user_role
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int insert(BtSysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user_role
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int insertSelective(BtSysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user_role
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    List<BtSysUserRole> selectByExample(BtSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user_role
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtSysUserRole record, @Param("example") BtSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user_role
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int updateByExample(@Param("record") BtSysUserRole record, @Param("example") BtSysUserRoleExample example);


    /**
     * 根据用户ID进行查询
     * @param userId
     * @return
     */
    @Select("select * from bt_sys_user_role where user_id = #{userId}")
    List<BtSysUserRole> findByUserId(@Param("userId") String userId);

    /**
     * 根据用户ID修改角色ID
     * @param userId
     * @param roleId
     * @return
     */
    @Update("update bt_sys_user_role set role_id = #{roleId} where user_id = #{userId}")
    int updateByUserId(@Param("userId") String userId, @Param("roleId") String roleId);
}