package com.ch.dao;

import com.ch.dao.provider.BtSysUserProvider;
import com.ch.entity.BtSysUser;
import com.ch.entity.BtSysUserExample;

import java.util.Date;
import java.util.List;

import com.ch.model.PersonMangeDTO;
import com.ch.model.RolePermissionModel;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Repository;

@Repository
public interface BtSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user
     *
     * @mbg.generated Fri Mar 15 09:33:19 CST 2019
     */
    long countByExample(BtSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user
     *
     * @mbg.generated Fri Mar 15 09:33:19 CST 2019
     */
    int deleteByExample(BtSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user
     *
     * @mbg.generated Fri Mar 15 09:33:19 CST 2019
     */
    int insert(BtSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user
     *
     * @mbg.generated Fri Mar 15 09:33:19 CST 2019
     */
    int insertSelective(BtSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user
     *
     * @mbg.generated Fri Mar 15 09:33:19 CST 2019
     */
    List<BtSysUser> selectByExample(BtSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user
     *
     * @mbg.generated Fri Mar 15 09:33:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtSysUser record, @Param("example") BtSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_user
     *
     * @mbg.generated Fri Mar 15 09:33:19 CST 2019
     */
    int updateByExample(@Param("record") BtSysUser record, @Param("example") BtSysUserExample example);

    /**
     * 根据用户ID进行查询
     * @param userId
     * @return
     */
    @Select("select * from bt_sys_user where user_id = #{userId}")
    BtSysUser findByUserId(@Param("userId") String userId);

    /**
     * 后台用户列表查询
     * @param userName
     * @param roleId
     * @return
     */
    @SelectProvider(type = BtSysUserProvider.class, method = "getUserList")
    @Results({
            @Result(column = "username", property = "userName", javaType = String.class),
            @Result(column = "phone", property = "phone", javaType = String.class),
            @Result(column = "role_desc", property = "roleName", javaType = String.class),
            @Result(column = "account", property = "account", javaType = String.class),
            @Result(column = "status", property = "status", javaType = Integer.class),
            @Result(column = "update_time", property = "createDate", javaType = String.class),
            @Result(column = "user_id", property = "userId", javaType = String.class),
            @Result(column = "role_id", property = "roleId", javaType = String.class)
    })
    List<PersonMangeDTO> btUserList(@Param("userName") String userName, @Param("roleId") String roleId);

    /**
     * 根据ID进行修改
     * @param btSysUser
     * @return
     */
    @Update("update bt_sys_user set username = #{btSysUser.username}, " +
            " phone = #{btSysUser.phone}, account = #{btSysUser.account}, salt = #{btSysUser.salt}," +
            " password = #{btSysUser.password}, status = #{btSysUser.status} where user_id = #{btSysUser.userId}")
    Integer updateBtSysUserByUserId(@Param("btSysUser") BtSysUser btSysUser);


    /**
     * 后台重置密码
     * @param userId
     * @return
     */
    @Update("update bt_sys_user set password = '@g0c211aa0bc22ccb@0g5F4*1fcf3@24c@#@2g1aa06a2dc20@66#*d0@4c2c216', salt = '0bdf8d16-159d-4ebe-8a93-506a14d1df2d' where user_id = #{userId}")
    int resetPassword(@Param("userId") String userId);

    /**
     * 后台修改人员状态
     * @param userId
     * @return
     */
    @Update("update bt_sys_user set password = #{status} where user_id = #{userId}")
    int updateStatus(@Param("userId") String userId, @Param("status") int status);

    /**
     * 根据角色ID查询对应权限
     * @param roleId
     * @return
     */
    @Select("select bsrp.role_id,bsp.permission_id,bsp.name,bsp.parent_id,bsp.sort from bt_sys_role_permission bsrp" +
            "  left join bt_sys_permission bsp on bsp.permission_id = bsrp.permission_id where bsrp.role_id = #{roleId}")
    @Results({
            @Result(column = "role_id", property = "roleId", javaType = String.class),
            @Result(column = "permission_id", property = "permissionId", javaType = String.class),
            @Result(column = "name", property = "permissionName", javaType = String.class),
            @Result(column = "parent_id", property = "parentId", javaType = Integer.class),
            @Result(column = "sort", property = "sortOrder", javaType = Integer.class)
    })
    List<RolePermissionModel> findAllByRoleId(@Param("roleId") String roleId);

    /**
     * 查询所有角色权限
     * @return
     */
    @Select("select permission_id,name,parent_id,sort from bt_sys_permission")
    @Results({
            @Result(column = "permission_id", property = "permissionId", javaType = String.class),
            @Result(column = "name", property = "permissionName", javaType = String.class),
            @Result(column = "parent_id", property = "parentId", javaType = Integer.class),
            @Result(column = "sort", property = "sortOrder", javaType = Integer.class)
    })
    List<RolePermissionModel> findAll();


    @Select("select * from bt_sys_user where account = #{account}")
    BtSysUser findByAccount(@Param("account") String account);
}