package com.ch.dao;

import com.ch.entity.BtSysRolePermission;
import com.ch.entity.BtSysRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface BtSysRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_role_permission
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    long countByExample(BtSysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_role_permission
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int deleteByExample(BtSysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_role_permission
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int insert(BtSysRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_role_permission
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int insertSelective(BtSysRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_role_permission
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    List<BtSysRolePermission> selectByExample(BtSysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_role_permission
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtSysRolePermission record, @Param("example") BtSysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_role_permission
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int updateByExample(@Param("record") BtSysRolePermission record, @Param("example") BtSysRolePermissionExample example);
}