package com.ch.dao;

import com.ch.entity.BtSysPermission;
import com.ch.entity.BtSysPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

@Repository
public interface BtSysPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_permission
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    long countByExample(BtSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_permission
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int deleteByExample(BtSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_permission
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int insert(BtSysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_permission
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int insertSelective(BtSysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_permission
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    List<BtSysPermission> selectByExample(BtSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_permission
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtSysPermission record, @Param("example") BtSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_sys_permission
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int updateByExample(@Param("record") BtSysPermission record, @Param("example") BtSysPermissionExample example);

    /**
     * 根据ID进行查询
     * @param id
     * @return
     */
    @Select("select * from bt_sys_permission where permission_id = #{id}")
    BtSysPermission findById(@Param("id") String id);
}