package com.ch.dao;

import com.ch.entity.BtViewMenuEng;
import com.ch.entity.BtViewMenuEngExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

@Repository
public interface BtViewMenuEngMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu_eng
     *
     * @mbg.generated Thu Mar 21 14:40:43 CST 2019
     */
    long countByExample(BtViewMenuEngExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu_eng
     *
     * @mbg.generated Thu Mar 21 14:40:43 CST 2019
     */
    int deleteByExample(BtViewMenuEngExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu_eng
     *
     * @mbg.generated Thu Mar 21 14:40:43 CST 2019
     */
    int insert(BtViewMenuEng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu_eng
     *
     * @mbg.generated Thu Mar 21 14:40:43 CST 2019
     */
    int insertSelective(BtViewMenuEng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu_eng
     *
     * @mbg.generated Thu Mar 21 14:40:43 CST 2019
     */
    List<BtViewMenuEng> selectByExample(BtViewMenuEngExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu_eng
     *
     * @mbg.generated Thu Mar 21 14:40:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtViewMenuEng record, @Param("example") BtViewMenuEngExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu_eng
     *
     * @mbg.generated Thu Mar 21 14:40:43 CST 2019
     */
    int updateByExample(@Param("record") BtViewMenuEng record, @Param("example") BtViewMenuEngExample example);


    int deleteByPrimaryKey(String id);


    @Select("select * from bt_view_menu_eng where id = #{id}")
    BtViewMenuEng findById(@Param("id") String id);

    int updateByPrimaryKey(BtViewMenuEng btViewMenuEng);
}