package com.ch.dao;

import com.ch.dao.provider.BtViewMessageProvider;
import com.ch.entity.BtViewMessage;
import com.ch.entity.BtViewMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectProvider;
import org.springframework.stereotype.Repository;

@Repository
public interface BtViewMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_message
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    long countByExample(BtViewMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_message
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int deleteByExample(BtViewMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_message
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int insert(BtViewMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_message
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int insertSelective(BtViewMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_message
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    List<BtViewMessage> selectByExampleWithBLOBs(BtViewMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_message
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    List<BtViewMessage> selectByExample(BtViewMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_message
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtViewMessage record, @Param("example") BtViewMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_message
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") BtViewMessage record, @Param("example") BtViewMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_message
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int updateByExample(@Param("record") BtViewMessage record, @Param("example") BtViewMessageExample example);

    @SelectProvider(type = BtViewMessageProvider.class, method = "getMessageList")
    List<BtViewMessage> findAll(@Param("name") String name, @Param("phone") String phone);
}