package com.ch.dao;

import com.ch.entity.BtViewNewsCategory;
import com.ch.entity.BtViewNewsCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface BtViewNewsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    long countByExample(BtViewNewsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int deleteByExample(BtViewNewsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int insert(BtViewNewsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int insertSelective(BtViewNewsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    List<BtViewNewsCategory> selectByExample(BtViewNewsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtViewNewsCategory record, @Param("example") BtViewNewsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int updateByExample(@Param("record") BtViewNewsCategory record, @Param("example") BtViewNewsCategoryExample example);

     int updateByPrimaryKey(BtViewNewsCategory record);


     int deleteByPrimaryKey(Integer id);

}