package com.ch.dao;

import com.ch.entity.BtViewNewsEng;
import com.ch.entity.BtViewNewsEngExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

@Repository
public interface BtViewNewsEngMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_eng
     *
     * @mbg.generated Thu Mar 21 14:40:43 CST 2019
     */
    long countByExample(BtViewNewsEngExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_eng
     *
     * @mbg.generated Thu Mar 21 14:40:43 CST 2019
     */
    int deleteByExample(BtViewNewsEngExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_eng
     *
     * @mbg.generated Thu Mar 21 14:40:43 CST 2019
     */
    int insert(BtViewNewsEng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_eng
     *
     * @mbg.generated Thu Mar 21 14:40:43 CST 2019
     */
    int insertSelective(BtViewNewsEng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_eng
     *
     * @mbg.generated Thu Mar 21 14:40:43 CST 2019
     */
    List<BtViewNewsEng> selectByExample(BtViewNewsEngExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_eng
     *
     * @mbg.generated Thu Mar 21 14:40:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtViewNewsEng record, @Param("example") BtViewNewsEngExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_eng
     *
     * @mbg.generated Thu Mar 21 14:40:43 CST 2019
     */
    int updateByExample(@Param("record") BtViewNewsEng record, @Param("example") BtViewNewsEngExample example);

    /**
     * 根据主键查询
     * @param id
     * @return
     */
    @Select("select * from bt_view_news_eng where id = #{id}")
    BtViewNewsEng findById(@Param("id") String id);

    @Update("update bt_view_news_eng set status = #{btViewNewsEng.status}, new_content = #{btViewNewsEng.newContent}," +
            " title = #{btViewNewsEng.title}, update_time = #{btViewNewsEng.updateTime}, status_str = #{btViewNewsEng.statusStr}," +
            " picture_url = #{btViewNewsEng.pictureUrl}, new_category_id = #{btViewNewsEng.newCategoryId}, menu_id = #{btViewNewsEng.menuId}," +
            " browse_number = #{btViewNewsEng.browseNumber}, create_time = #{btViewNewsEng.createTime}  where id = #{btViewNewsEng.id}")
    int updateByPrimaryKey(@Param("btViewNewsEng") BtViewNewsEng btViewNewsEng);


    @Update("update bt_view_news_eng set status = #{status} where id = #{id}" )
    int updateStatus (@Param("id") String id,@Param("status") int status);

    @Update("update bt_view_news_eng set status = 0 where menu_id = #{menuId}")
    int updateUnpublished(@Param("menuId") String menuId);

}