package com.ch.dao;

import java.sql.Date;
import java.util.List;

import com.ch.base.ResponseResult;
import com.ch.dao.provider.BtViewNewsProvider;
import com.ch.dto.NewsParam;
import com.ch.entity.BtViewNews;
import com.ch.entity.BtViewNewsExample;
import com.ch.model.NewsPageDTO;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

@Repository
public interface BtViewNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Thu Mar 14 14:09:05 CST 2019
     */
    long countByExample(BtViewNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Thu Mar 14 14:09:05 CST 2019
     */
    int deleteByExample(BtViewNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Thu Mar 14 14:09:05 CST 2019
     */
    int insert(BtViewNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Thu Mar 14 14:09:05 CST 2019
     */
    int insertSelective(BtViewNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Thu Mar 14 14:09:05 CST 2019
     */
    List<BtViewNews> selectByExample(BtViewNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Thu Mar 14 14:09:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtViewNews record, @Param("example") BtViewNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Thu Mar 14 14:09:05 CST 2019
     */

    int updateByExample(@Param("record") BtViewNews record, @Param("example") BtViewNewsExample example);


    int updateByPrimaryKey(BtViewNews record);

    BtViewNews selectByPrimaryKey (@Param("id") String id);

    @Update("update bt_view_news set status = #{status} , update_time = now() where id = #{id}" )
    int updateStatus (@Param("id") String id, @Param("status") int status);

    @Update("update bt_view_news set status = #{status}, update_time = null  where id = #{id}" )
    int updateDate (@Param("id") String id, @Param("status") int status);

    @Select("select * from bt_view_news where id = #{id}")
    BtViewNews findById(@Param("id") String id);

    @Update("update bt_view_news set status = 0 ,update_time = null  where menu_id = #{menuId}")
    int updateUnpublished(@Param("menuId") String menuId);

    @SelectProvider(type = BtViewNewsProvider.class , method = "getNewsList")
    List<NewsPageDTO> findPage(@Param("newsParam")NewsParam newsParam);
}