package com.ch.entity;

public class BtSysUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_user_role.user_id
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_user_role.role_id
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_user_role.user_id
     *
     * @return the value of bt_sys_user_role.user_id
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_user_role.user_id
     *
     * @param userId the value for bt_sys_user_role.user_id
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_user_role.role_id
     *
     * @return the value of bt_sys_user_role.role_id
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_user_role.role_id
     *
     * @param roleId the value for bt_sys_user_role.role_id
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}