package com.ch.entity;

import java.util.Date;

public class BtSysTrafficStatistics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_traffic_statistics.id
     *
     * @mbg.generated Mon Mar 18 10:11:12 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_traffic_statistics.ip
     *
     * @mbg.generated Mon Mar 18 10:11:12 CST 2019
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_traffic_statistics.region
     *
     * @mbg.generated Mon Mar 18 10:11:12 CST 2019
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_traffic_statistics.create_date
     *
     * @mbg.generated Mon Mar 18 10:11:12 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_sys_traffic_statistics.browsing_time
     *
     * @mbg.generated Mon Mar 18 10:11:12 CST 2019
     */
    private Long browsingTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_traffic_statistics.id
     *
     * @return the value of bt_sys_traffic_statistics.id
     *
     * @mbg.generated Mon Mar 18 10:11:12 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_traffic_statistics.id
     *
     * @param id the value for bt_sys_traffic_statistics.id
     *
     * @mbg.generated Mon Mar 18 10:11:12 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_traffic_statistics.ip
     *
     * @return the value of bt_sys_traffic_statistics.ip
     *
     * @mbg.generated Mon Mar 18 10:11:12 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_traffic_statistics.ip
     *
     * @param ip the value for bt_sys_traffic_statistics.ip
     *
     * @mbg.generated Mon Mar 18 10:11:12 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_traffic_statistics.region
     *
     * @return the value of bt_sys_traffic_statistics.region
     *
     * @mbg.generated Mon Mar 18 10:11:12 CST 2019
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_traffic_statistics.region
     *
     * @param region the value for bt_sys_traffic_statistics.region
     *
     * @mbg.generated Mon Mar 18 10:11:12 CST 2019
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_traffic_statistics.create_date
     *
     * @return the value of bt_sys_traffic_statistics.create_date
     *
     * @mbg.generated Mon Mar 18 10:11:12 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_traffic_statistics.create_date
     *
     * @param createDate the value for bt_sys_traffic_statistics.create_date
     *
     * @mbg.generated Mon Mar 18 10:11:12 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_sys_traffic_statistics.browsing_time
     *
     * @return the value of bt_sys_traffic_statistics.browsing_time
     *
     * @mbg.generated Mon Mar 18 10:11:12 CST 2019
     */
    public Long getBrowsingTime() {
        return browsingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_sys_traffic_statistics.browsing_time
     *
     * @param browsingTime the value for bt_sys_traffic_statistics.browsing_time
     *
     * @mbg.generated Mon Mar 18 10:11:12 CST 2019
     */
    public void setBrowsingTime(Long browsingTime) {
        this.browsingTime = browsingTime;
    }
}