package com.ch.entity;

public class BtViewNewsCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_news_category.id
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_news_category.news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    private String newsCategory;

    private  String categoryDesc;

    public String getCategoryDesc() {
        return categoryDesc;
    }

    public void setCategoryDesc(String categoryDesc) {
        this.categoryDesc = categoryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news_category.id
     *
     * @return the value of bt_view_news_category.id
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news_category.id
     *
     * @param id the value for bt_view_news_category.id
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_news_category.news_category
     *
     * @return the value of bt_view_news_category.news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public String getNewsCategory() {
        return newsCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_news_category.news_category
     *
     * @param newsCategory the value for bt_view_news_category.news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setNewsCategory(String newsCategory) {
        this.newsCategory = newsCategory == null ? null : newsCategory.trim();
    }
}