package com.ch.entity;

import java.util.Date;

public class BtViewMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.id
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.name
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.tel
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.email
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.company
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.message_time
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    private Date messageTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.address
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.gender
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.QQ
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.id_card
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.wechat
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_view_message.content
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.id
     *
     * @return the value of bt_view_message.id
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.id
     *
     * @param id the value for bt_view_message.id
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.name
     *
     * @return the value of bt_view_message.name
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.name
     *
     * @param name the value for bt_view_message.name
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.tel
     *
     * @return the value of bt_view_message.tel
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.tel
     *
     * @param tel the value for bt_view_message.tel
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.email
     *
     * @return the value of bt_view_message.email
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.email
     *
     * @param email the value for bt_view_message.email
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.company
     *
     * @return the value of bt_view_message.company
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.company
     *
     * @param company the value for bt_view_message.company
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.message_time
     *
     * @return the value of bt_view_message.message_time
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public Date getMessageTime() {
        return messageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.message_time
     *
     * @param messageTime the value for bt_view_message.message_time
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setMessageTime(Date messageTime) {
        this.messageTime = messageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.address
     *
     * @return the value of bt_view_message.address
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.address
     *
     * @param address the value for bt_view_message.address
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.gender
     *
     * @return the value of bt_view_message.gender
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.gender
     *
     * @param gender the value for bt_view_message.gender
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.QQ
     *
     * @return the value of bt_view_message.QQ
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.QQ
     *
     * @param qq the value for bt_view_message.QQ
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.id_card
     *
     * @return the value of bt_view_message.id_card
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.id_card
     *
     * @param idCard the value for bt_view_message.id_card
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.wechat
     *
     * @return the value of bt_view_message.wechat
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.wechat
     *
     * @param wechat the value for bt_view_message.wechat
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_view_message.content
     *
     * @return the value of bt_view_message.content
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_view_message.content
     *
     * @param content the value for bt_view_message.content
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}