package com.ch.entity;

import java.util.ArrayList;
import java.util.List;

public class BtViewNewsCategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public BtViewNewsCategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNewsCategoryIsNull() {
            addCriterion("news_category is null");
            return (Criteria) this;
        }

        public Criteria andNewsCategoryIsNotNull() {
            addCriterion("news_category is not null");
            return (Criteria) this;
        }

        public Criteria andNewsCategoryEqualTo(String value) {
            addCriterion("news_category =", value, "newsCategory");
            return (Criteria) this;
        }

        public Criteria andNewsCategoryNotEqualTo(String value) {
            addCriterion("news_category <>", value, "newsCategory");
            return (Criteria) this;
        }

        public Criteria andNewsCategoryGreaterThan(String value) {
            addCriterion("news_category >", value, "newsCategory");
            return (Criteria) this;
        }

        public Criteria andNewsCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("news_category >=", value, "newsCategory");
            return (Criteria) this;
        }

        public Criteria andNewsCategoryLessThan(String value) {
            addCriterion("news_category <", value, "newsCategory");
            return (Criteria) this;
        }

        public Criteria andNewsCategoryLessThanOrEqualTo(String value) {
            addCriterion("news_category <=", value, "newsCategory");
            return (Criteria) this;
        }

        public Criteria andNewsCategoryLike(String value) {
            addCriterion("news_category like", value, "newsCategory");
            return (Criteria) this;
        }

        public Criteria andNewsCategoryNotLike(String value) {
            addCriterion("news_category not like", value, "newsCategory");
            return (Criteria) this;
        }

        public Criteria andNewsCategoryIn(List<String> values) {
            addCriterion("news_category in", values, "newsCategory");
            return (Criteria) this;
        }

        public Criteria andNewsCategoryNotIn(List<String> values) {
            addCriterion("news_category not in", values, "newsCategory");
            return (Criteria) this;
        }

        public Criteria andNewsCategoryBetween(String value1, String value2) {
            addCriterion("news_category between", value1, value2, "newsCategory");
            return (Criteria) this;
        }

        public Criteria andNewsCategoryNotBetween(String value1, String value2) {
            addCriterion("news_category not between", value1, value2, "newsCategory");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bt_view_news_category
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 13 11:57:15 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bt_view_news_category
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}