package com.ch.service;

import com.ch.base.ResponseResult;
import com.ch.dto.MenuParam;
import com.ch.dto.NewsParam;
import com.ch.entity.BtViewMenu;
import com.ch.entity.BtViewMenuExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BtViewMenuService {
    long countByExample(BtViewMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int deleteByExample(BtViewMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int insertSelective(BtViewMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    List<BtViewMenu> selectByExample(BtViewMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtViewMenu record, @Param("example") BtViewMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_menu
     *
     * @mbg.generated Wed Mar 13 11:57:15 CST 2019
     */
    int updateByExample(@Param("record") BtViewMenu record, @Param("example") BtViewMenuExample example);


    /**
     * 展示网站首页菜单
     * @return
     */
    ResponseResult findTree();

    ResponseResult findTreeEng();
    ResponseResult findTreeFan();

    /**
     * 分页展示菜单
     * @return
     */
    public ResponseResult findPageTree(int pageNum, int pageSize);
    /**
     * 分页展示查询结果
     * @return
     */
    public ResponseResult findPage(MenuParam menuParam);

    /**
     * 修改
     * @param btViewMenu
     * @return
     */
    public ResponseResult updateByPrimaryKey(BtViewMenu btViewMenu);

    /**
     * 增加
     * @param record
     * @return
     */
    public ResponseResult insert(BtViewMenu record);

    /**
     * 删除
     */
    public ResponseResult  deleteByPrimaryKey(String id);

}


