package com.ch.service;

import com.ch.base.ResponseResult;
import com.ch.entity.BtViewNews;
import com.ch.entity.BtViewNewsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BtViewNewsService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    long countByExample(BtViewNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    int deleteByExample(BtViewNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    int insert(BtViewNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    int insertSelective(BtViewNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    List<BtViewNews> selectByExampleWithBLOBs(BtViewNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    List<BtViewNews> selectByExample(BtViewNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") BtViewNews record, @Param("example") BtViewNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") BtViewNews record, @Param("example") BtViewNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_view_news
     *
     * @mbg.generated Wed Mar 13 14:38:56 CST 2019
     */
    int updateByExample(@Param("record") BtViewNews record, @Param("example") BtViewNewsExample example);

    public ResponseResult findViewNewsByNewId(String newId);

    /**
     * 根据ID查询英文信息
     * @param newId
     * @return
     */
    ResponseResult findViewNewsEngByNewId(String newId);

    ResponseResult findViewNewsFanByNewId(String newId);

    ResponseResult findViewNewsByMenId(String menuId, Integer index, Integer size);

    ResponseResult findViewNewsEngByMenId(String menuId, Integer index, Integer size);

    ResponseResult findViewNewsFanByMenId(String menuId, Integer index, Integer size);

    ResponseResult findOneByMenId(String menuId);

    ResponseResult findOneEngByMenId(String menuId);

    ResponseResult findOneFanByMenId(String menuId);


}
